version: '3'
services:
  node1:
    build: .
    env_file:
      - ./dtcnode.env
    volumes:
      - ./config/node1/:/etc/dtcnode/
    ports:
      - "9871:2030"
  node2:
    build: .
    env_file:
      - ./dtcnode.env
    volumes:
      - ./config/node2/:/etc/dtcnode/
    ports:
      - "9873:2030"
  node3:
    build: .
    env_file:
      - ./dtcnode.env
    volumes:
      - ./config/node3/:/etc/dtcnode/
    ports:
      - "9875:2030"
  node4:
    build: .
    env_file:
      - ./dtcnode.env
    volumes:
      - ./config/node4/:/etc/dtcnode/
    ports:
      - "9877:2030"
  node5:
    build: .
    env_file:
      - ./dtcnode.env
    volumes:
      - ./config/node5/:/etc/dtcnode/
    ports:
      - "9879:2030"

