version: '3'
services:
  node1:
    build:
      context: ../../
      dockerfile: ./dtcnode/docker/Dockerfile
    volumes:
      - ./config/node_0/:/etc/dtcnode/
    ports:
      - "9871:9871"
  node2:
    build:
      context: ../../
      dockerfile: ./dtcnode/docker/Dockerfile
    volumes:
      - ./config/node_1/:/etc/dtcnode/
    ports:
      - "9873:9873"
  node3:
    build:
      context: ../../
      dockerfile: ./dtcnode/docker/Dockerfile
    volumes:
      - ./config/node_2/:/etc/dtcnode/
    ports:
      - "9875:9875"
  node4:
    build:
      context: ../../
      dockerfile: ./dtcnode/docker/Dockerfile
    volumes:
      - ./config/node_3/:/etc/dtcnode/
    ports:
      - "9877:9877"
  node5:
    build:
      context: ../../
      dockerfile: ./dtcnode/docker/Dockerfile
    volumes:
      - ./config/node_4/:/etc/dtcnode/
    ports:
      - "9879:9879"

