config:
  publickey: <)wcHcA2J+mw+03CA70>G*2$<VIUj]98(9Ii5l1#
  privatekey: hNmLpP{)nq7[RSmeLtYABrvI3v@.^HJ&C&VB[^BT
  ip: ""
  port: 2030
  servers:
  - publickey: hola
    ip: ""
    port: 2031
    keys: []
  - publickey: mundo
    ip: ""
    port: 2032
    keys: []
  - publickey: "123"
    ip: ""
    port: 2033
    keys: []
